// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATestingSystem.Repository.TienDM.Models;

public partial class ProfileRelationshipThinhLc
{
    public int ProfileRelationshipThinhLcid { get; set; }

    public int ProfileThinhLcid1 { get; set; }

    public int ProfileThinhLcid2 { get; set; }

    public string RelationshipType { get; set; }

    public bool? ConfirmedByTest { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ProfileThinhLc ProfileThinhLcid1Navigation { get; set; }

    public virtual ProfileThinhLc ProfileThinhLcid2Navigation { get; set; }
}