// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DNATestingSystem.Repository.TienDM.Models;

public partial class ProfileThinhLc
{
    public int ProfileThinhLcid { get; set; }

    public int? UserAccountId { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string NationalId { get; set; }

    public bool IsDeceased { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ProfileRelationshipThinhLc> ProfileRelationshipThinhLcProfileThinhLcid1Navigations { get; set; } = new List<ProfileRelationshipThinhLc>();

    public virtual ICollection<ProfileRelationshipThinhLc> ProfileRelationshipThinhLcProfileThinhLcid2Navigations { get; set; } = new List<ProfileRelationshipThinhLc>();

    public virtual ICollection<SampleThinhLc> SampleThinhLcs { get; set; } = new List<SampleThinhLc>();

    public virtual UserAccount UserAccount { get; set; }
}